server.port: 8443
security.require-ssl=true
server.ssl.key-store:classpath:cert.p12
server.ssl.key-store-password: password
server.ssl.keyStoreType: PKCS12
server.ssl.keyAlias: tomcat

# Max Request Size
spring.servlet.multipart.max-request-size=500MB