name: Feature Request
title: "[FEATURE] "
description: Suggest an idea for SpotifyDownloader
labels: ["enhancement"]
assignees: ["2Friendly4You"]
body:
  - type: dropdown
    attributes:
      label: Feature Category
      description: What area of the application does this feature relate to?
      options:
        - Download Functionality
        - User Interface
        - Format Support
        - Provider Integration
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see added
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: This would be useful when...
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical
        - High
        - Medium
        - Low
        - Nice to have
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: Screenshots, mock-ups, or additional details...